#!/usr/bin/env bash

# Shared logging helpers for WXF MQTT launchers.
#
# This file is sourced by:
#   run_live_task.sh
#   run_live_script.sh
#   run_dry_script.sh
#
# It records every run under:
#   /data/wxf/wxf/mqtt_gateway_workspace_20260624/run_logs/YYYYMMDD/
#
# The logs are intentionally plain text. When something fails, send the latest
# log file or a debug bundle generated by collect_debug_bundle.sh.

wxf__safe_name() {
  printf '%s' "$1" | sed 's/[^A-Za-z0-9_.-]/_/g' | cut -c 1-80
}

wxf_log_init() {
  WXF_LOG_ROOT="$1"
  WXF_LOG_MODE="$2"
  WXF_LOG_LABEL="$(wxf__safe_name "$3")"
  WXF_LOG_STARTED_AT="$(date '+%Y-%m-%d %H:%M:%S %Z')"
  WXF_LOG_RUN_ID="$(date '+%Y%m%d_%H%M%S')_${WXF_LOG_MODE}_${WXF_LOG_LABEL}_$$"
  WXF_LOG_DIR="${WXF_LOG_ROOT}/run_logs/$(date '+%Y%m%d')"
  WXF_LOG_FILE="${WXF_LOG_DIR}/${WXF_LOG_RUN_ID}.log"
  mkdir -p "${WXF_LOG_DIR}"
  export WXF_LAST_RUN_LOG="${WXF_LOG_FILE}"
}

wxf_log() {
  printf '%s\n' "$*" | tee -a "${WXF_LOG_FILE}"
}

wxf_log_file_only() {
  printf '%s\n' "$*" >> "${WXF_LOG_FILE}"
}

wxf_log_section() {
  wxf_log ""
  wxf_log "===== $* ====="
}

wxf_log_command_context() {
  local cwd="$1"
  shift

  wxf_log_section "run context"
  wxf_log "started_at: ${WXF_LOG_STARTED_AT}"
  wxf_log "run_id: ${WXF_LOG_RUN_ID}"
  wxf_log "mode: ${WXF_LOG_MODE}"
  wxf_log "workspace: ${WXF_LOG_ROOT}"
  wxf_log "cwd: ${cwd}"
  wxf_log "command: $*"
  wxf_log "user: $(id -un 2>/dev/null || true)"
  wxf_log "host: $(hostname 2>/dev/null || true)"
  wxf_log "pwd_before_cd: $(pwd)"

  wxf_log_section "selected environment"
  {
    env | sort | grep -E '^(G2_WXF_|G2_GATEWAY_|PYTHONPATH=|PATH=|USER=|HOME=|PWD=)' || true
  } | tee -a "${WXF_LOG_FILE}"
}

wxf_log_service_snapshot() {
  wxf_log_section "service snapshot before run"
  {
    echo "# systemctl is-active"
    systemctl is-active mosquitto g2-industrial-gateway.service g2-industrial-gateway-mqtt.service 2>&1 || true
    echo
    echo "# systemctl is-enabled"
    systemctl is-enabled mosquitto g2-industrial-gateway.service g2-industrial-gateway-mqtt.service 2>&1 || true
    echo
    echo "# ports"
    ss -ltnp 2>/dev/null | grep -E ':(8767|1883)' || true
    echo
    echo "# gateway /api/ready"
    curl -sS --max-time 3 http://127.0.0.1:8767/api/ready 2>&1 || true
    echo
    echo "# gateway /api/runtime"
    curl -sS --max-time 3 http://127.0.0.1:8767/api/runtime 2>&1 || true
  } >> "${WXF_LOG_FILE}"
  wxf_log "# service snapshot saved in log"
}

wxf_log_robot_readonly_snapshot() {
  local phase="$1"
  wxf_log_section "robot readonly snapshot ${phase}"
  {
    echo "# ${phase} snapshot captured_at: $(date '+%Y-%m-%d %H:%M:%S %Z')"
    echo
    for command in \
      gdk.read_power_state \
      gdk.read_task_state \
      gdk.read_motion_status \
      gdk.read_joint_states
    do
      echo "# ${command}"
      timeout 12 python3 "${WXF_LOG_ROOT}/gateway_mqtt_client.py" \
        --command "${command}" \
        --mode read_only \
        --args-json '{}' \
        --timeout-s 8 \
        --preflight warn 2>&1 || true
      echo
    done
  } >> "${WXF_LOG_FILE}"
  wxf_log "# ${phase} readonly snapshot saved in log"
}

wxf_log_failure_diagnostics() {
  local rc="$1"
  wxf_log_section "failure diagnostics"
  {
    echo "exit_code: ${rc}"
    echo
    echo "# gateway /api/ready after failure"
    curl -sS --max-time 3 http://127.0.0.1:8767/api/ready 2>&1 || true
    echo
    echo "# gateway /api/tasks after failure"
    curl -sS --max-time 3 http://127.0.0.1:8767/api/tasks 2>&1 || true
    echo
    echo "# journalctl g2-industrial-gateway.service tail"
    journalctl -u g2-industrial-gateway.service -n 120 --no-pager 2>&1 || true
    echo
    echo "# journalctl g2-industrial-gateway-mqtt.service tail"
    journalctl -u g2-industrial-gateway-mqtt.service -n 120 --no-pager 2>&1 || true
    echo
    echo "# journalctl mosquitto tail"
    journalctl -u mosquitto -n 80 --no-pager 2>&1 || true
  } >> "${WXF_LOG_FILE}"
  wxf_log "# failure diagnostics appended to log"
}

wxf_append_run_index() {
  local rc="$1"
  local cwd="$2"
  shift 2
  local command_string="$*"
  local finished_at
  finished_at="$(date '+%Y-%m-%d %H:%M:%S %Z')"
  local index_file="${WXF_LOG_ROOT}/run_logs/runs.jsonl"
  python3 - \
    "${index_file}" \
    "${WXF_LOG_RUN_ID}" \
    "${WXF_LOG_MODE}" \
    "${WXF_LOG_LABEL}" \
    "${WXF_LOG_STARTED_AT}" \
    "${finished_at}" \
    "${rc}" \
    "${cwd}" \
    "${command_string}" \
    "${WXF_LOG_FILE}" <<'PY'
import json
import sys
from pathlib import Path

index_file, run_id, mode, label, started_at, finished_at, rc, cwd, command, log_file = sys.argv[1:]
payload = {
    "run_id": run_id,
    "mode": mode,
    "label": label,
    "started_at": started_at,
    "finished_at": finished_at,
    "exit_code": int(rc),
    "cwd": cwd,
    "command": command,
    "log_file": log_file,
}
path = Path(index_file)
path.parent.mkdir(parents=True, exist_ok=True)
with path.open("a", encoding="utf-8") as f:
    f.write(json.dumps(payload, ensure_ascii=False, sort_keys=True) + "\n")
PY
}

wxf_run_logged() {
  local cwd="$1"
  shift

  wxf_log_command_context "${cwd}" "$@"
  wxf_log_service_snapshot
  wxf_log_robot_readonly_snapshot "before"

  wxf_log_section "script output"
  cd "${cwd}"
  set +e
  "$@" 2>&1 | tee -a "${WXF_LOG_FILE}"
  local rc=${PIPESTATUS[0]}
  set -e
  wxf_log_robot_readonly_snapshot "after"

  wxf_log_section "run result"
  wxf_log "finished_at: $(date '+%Y-%m-%d %H:%M:%S %Z')"
  wxf_log "exit_code: ${rc}"
  wxf_log "log_file: ${WXF_LOG_FILE}"

  if [[ "${rc}" -ne 0 ]]; then
    wxf_log_failure_diagnostics "${rc}"
  fi

  wxf_append_run_index "${rc}" "${cwd}" "$@"
  return "${rc}"
}
